// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace Parkor
{
public static class GPGSIds
{
        public const string achievement_arena = "CgkIwt3e_8MYEAIQDQ"; // <GPGSID>
        public const string achievement_ilk_kan = "CgkIwt3e_8MYEAIQBQ"; // <GPGSID>
        public const string achievement_bcek_patron = "CgkIwt3e_8MYEAIQCA"; // <GPGSID>
        public const string achievement_yuva_ykan = "CgkIwt3e_8MYEAIQCg"; // <GPGSID>
        public const string achievement_ka = "CgkIwt3e_8MYEAIQBw"; // <GPGSID>
        public const string achievement_tanr_yaratk = "CgkIwt3e_8MYEAIQBg"; // <GPGSID>
        public const string achievement_nesil_tketen = "CgkIwt3e_8MYEAIQCw"; // <GPGSID>
        public const string achievement_sezon_1 = "CgkIwt3e_8MYEAIQDA"; // <GPGSID>
        public const string achievement_rmcek_katili = "CgkIwt3e_8MYEAIQCQ"; // <GPGSID>

}
}
